"""empty message

Revision ID: 44a936bba248
Revises: 
Create Date: 2023-06-21 03:36:09.708837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44a936bba248'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endereco')
    op.drop_table('cidade')
    op.drop_table('imovel')
    op.drop_table('anuncio')
    op.drop_table('estado')
    op.drop_table('bairro')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.CHAR(length=11),
               type_=sa.String(length=11),
               existing_nullable=True)
        batch_op.alter_column('tel',
               existing_type=sa.CHAR(length=11),
               type_=sa.String(length=11),
               existing_nullable=True)
        batch_op.alter_column('senha',
               existing_type=sa.CHAR(length=45),
               type_=sa.String(length=45),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=45),
               type_=sa.CHAR(length=45),
               existing_nullable=True)
        batch_op.alter_column('tel',
               existing_type=sa.String(length=11),
               type_=sa.CHAR(length=11),
               existing_nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=11),
               type_=sa.CHAR(length=11),
               existing_nullable=True)

    op.create_table('bairro',
    sa.Column('idbairro', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idbairro', name='bairro_pkey')
    )
    op.create_table('estado',
    sa.Column('idestado', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idestado', name='estado_pkey')
    )
    op.create_table('anuncio',
    sa.Column('idanuncio', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipoanuncio', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('imovel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idanuncio', name='anuncio_pkey')
    )
    op.create_table('imovel',
    sa.Column('idimovel', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipoimovel', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('valorimovel', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('dadovendedor', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('enderecoimovel', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('quantquarto', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('quantgaragem', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('descgaragem', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('quantisuite', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('quantobanheiro', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('areaservico', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('piscina', postgresql.ENUM('Sim', 'Não', name='mood'), autoincrement=False, nullable=True),
    sa.Column('internet', postgresql.ENUM('Sim', 'Não', name='mood'), autoincrement=False, nullable=True),
    sa.Column('mobiliado', postgresql.ENUM('Sim', 'Não', name='mood'), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endereco_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idimovel', name='imovel_pkey')
    )
    op.create_table('cidade',
    sa.Column('idcidade', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idcidade', name='cidade_pkey')
    )
    op.create_table('endereco',
    sa.Column('idendereco', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('logradouro', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cep', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('cidade_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bairro_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idendereco', name='endereco_pkey')
    )
    # ### end Alembic commands ###
